export const FrontoVariants = ['display', 'input', 'cell'] as const
export type FrontoComponentVariant = (typeof FrontoVariants)[number]

export const StrictoTypes = ['Bool', 'Int', 'Float', 'String', 'Datetime', 'Bytes', 'Dict'] as const
export type FrontoStrictoType = (typeof StrictoTypes)[number]

export interface FrontoValidationMessage {
    path: string
    message: string
    code?: string
}

export interface FrontoFieldBase {
    strictoType: FrontoStrictoType
    label?: string
    description?: string
    required?: boolean
    readOnly?: boolean
}

export interface FrontoBoolField extends FrontoFieldBase {
    strictoType: 'Bool'
    defaultValue?: boolean
}

export interface FrontoIntField extends FrontoFieldBase {
    strictoType: 'Int'
    min?: number
    max?: number
    defaultValue?: number
}

export interface FrontoFloatField extends FrontoFieldBase {
    strictoType: 'Float'
    min?: number
    max?: number
    defaultValue?: number
}

export interface FrontoStringField extends FrontoFieldBase {
    strictoType: 'String'
    patterns?: string[]
    enumValues?: string[]
    defaultValue?: string
}

export interface FrontoDatetimeField extends FrontoFieldBase {
    strictoType: 'Datetime'
    defaultValue?: string
}

export interface FrontoBytesField extends FrontoFieldBase {
    strictoType: 'Bytes'
    defaultValue?: string
}

export interface FrontoDictField extends FrontoFieldBase {
    strictoType: 'Dict'
    fields: Record<string, FrontoFieldDefinition>
}

export type FrontoFieldDefinition =
    | FrontoBoolField
    | FrontoIntField
    | FrontoFloatField
    | FrontoStringField
    | FrontoDatetimeField
    | FrontoBytesField
    | FrontoDictField

export interface FrontoFieldState<TValue> {
    value: TValue
    validationMessages: FrontoValidationMessage[]
}

export interface FrontoComponentSource {
    strictoType: FrontoStrictoType
    variant: FrontoComponentVariant
    sourcePath: string
}

export const FRONTO_COMPONENTS_ROOT_PATH: string = 'fronto/components';

export const FRONTO_COMPONENTS_BASE_PATH: string = `${FRONTO_COMPONENTS_ROOT_PATH}/base`;

export const FRONTO_COMPONENTS_ITEMS_PATH: string = `${FRONTO_COMPONENTS_ROOT_PATH}/items`;

export const FRONTO_COMPONENTS_OVERRIDES_BASE_PATH: string = `${FRONTO_COMPONENTS_ROOT_PATH}/overrides/base`;

export const FRONTO_COMPONENTS_OVERRIDES_ITEMS_PATH: string = `${FRONTO_COMPONENTS_ROOT_PATH}/overrides/items`;

export const FRONTO_GENERATED_CODE_NOTICE: string = `\
// Fronto Components Registry
// Run \`fronto scan\` to regenerate
//
// AUTO-GENERATED BY FRONTO
// DO NOT EDIT
`

export type ComponentRegistry = Record<string, Record<string, string>>

export type FrontoTypeMap = {
    Bool: boolean
    Int: number
    Float: number
    String: string
    Datetime: string
    Bytes: string
    Dict: Record<string, unknown>
}

export interface FrontoComponentProps<TValue = unknown> {
    exist?: boolean
    readable?: boolean
    writable?: boolean
    required?: boolean
    description?: string
    errorMessage?: string
    defaultValue: TValue
    value?: TValue
    enum?: TValue[]
    onChange?: (value: TValue) => void
}

export type FrontoProps<T extends keyof FrontoTypeMap> = FrontoComponentProps<FrontoTypeMap[T]>

export const FRONTO_DEFAULT_PROPS = {
    exist: true,
    readable: true,
    writable: true,
    required: false,
    description: '',
    errorMessage: '',
    defaultValue: undefined,
    value: undefined,
    enum: undefined,
    onChange: undefined,
} satisfies Partial<FrontoComponentProps<unknown>>

export const FRONTO_TYPE_DEFAULTS = {
    Bool: {
        value: true,
        defaultValue: true,
        enum: [true, false],
    },
    Int: {
        value: 0,
        defaultValue: 0,
        enum: undefined,
    },
    Float: {
        value: 0,
        defaultValue: 0,
        enum: undefined,
    },
    String: {
        value: '',
        defaultValue: '',
        enum: undefined,
    },
    Datetime: {
        value: new Date(0).toISOString(),
        defaultValue: new Date(0).toISOString(),
        enum: undefined,
    },
    Bytes: {
        value: '',
        defaultValue: '',
        enum: undefined,
    },
    Dict: {
        value: {},
        defaultValue: {},
        enum: undefined,
    },
} satisfies Record<keyof FrontoTypeMap, Partial<FrontoComponentProps<unknown>>>

export function resolveFrontoProps<T extends keyof FrontoTypeMap>(
    type: T,
    provided?: Partial<FrontoComponentProps<FrontoTypeMap[T]>>,
): FrontoComponentProps<FrontoTypeMap[T]> {
    const typeDefaults = FRONTO_TYPE_DEFAULTS[type] || {}
    return {
        ...FRONTO_DEFAULT_PROPS,
        ...typeDefaults,
        ...provided,
    } as FrontoComponentProps<FrontoTypeMap[T]>
}


export function normalizeDatetimeToUtcIso(
    value: string | Date | null | undefined,
): string | null | undefined {
    if (value === undefined || value === null) {
        return value
    }

    const parsedDate = value instanceof Date ? value : new Date(value)
    if (Number.isNaN(parsedDate.getTime())) {
        throw new Error(`Invalid datetime value: ${String(value)}`)
    }

    return parsedDate.toISOString()
}

export function isBase64(value: string): boolean {
    if (value.length === 0) {
        return true
    }
    if (value.length % 4 !== 0) {
        return false
    }
    return /^[A-Za-z0-9+/]*={0,2}$/.test(value)
}

export function isValueInEnum<T extends keyof FrontoTypeMap>(
    value: FrontoTypeMap[T],
    enumValues: FrontoTypeMap[T][] | undefined,
): boolean {
    console.log('[CORE] isValueInEnum called with value:', value, 'and enumValues:', enumValues)
    if (enumValues === undefined) {
        return true
    }
    if (enumValues?.length === 0) {
        return false
    }
    return enumValues.some((enumValue) => {
        if (value instanceof Date && enumValue instanceof Date) {
            return value.getTime() === enumValue.getTime()
        }
        return value === enumValue
    })
}

